import asyncio
import logging
import tempfile
import time
import zipfile
from contextlib import suppress as contextlib_suppress
from pathlib import Path
from typing import Any

RUBIKA_ZIP_NAME = "NitoNumber-1.zip"

logging.getLogger("rubpy").setLevel(logging.INFO)
logging.getLogger("rubpy.network").setLevel(logging.INFO)

from rubpy import Client
from rubpy import exceptions as rubpy_exceptions
from rubpy.exceptions import RPCError

from App.config import Settings

logger = logging.getLogger(__name__)


class RubikaError(Exception):
    pass


class RubikaUploader:
    """Send files to Rubika users by their @username using the bot-owned account.

    Auth is via a pre-existing rubpy session file (`.rp`) generated by
    `session_rubika.py`. If the session file is missing, the uploader is
    disabled and no Telegram side-effects fire.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._client: Client | None = None
        self._lock = asyncio.Lock()
        self._connect_lock = asyncio.Lock()
        self._ready = False

    @property
    def session_path(self) -> Path:
        return self._settings.rubika_session_dir / f"{self._settings.rubika_session_name}.rp"

    @property
    def enabled(self) -> bool:
        return self.session_path.exists()

    async def connect(self) -> None:
        if self._ready and self._client is not None:
            return
        async with self._connect_lock:
            if self._ready and self._client is not None:
                return
            if not self.enabled:
                logger.info(
                    "[rubika] session file %s not present; uploader disabled. "
                    "Run `python session_rubika.py` to create it.",
                    self.session_path,
                )
                return
            self._settings.rubika_session_dir.mkdir(parents=True, exist_ok=True)
            session_name = str(
                self._settings.rubika_session_dir / self._settings.rubika_session_name
            )
            logger.info("[rubika] starting client (session=%s)", session_name)
            client = Client(session_name)
            try:
                await client.start()
                me = await client.get_me()
            except rubpy_exceptions.NotRegistered as exc:
                with contextlib_suppress(Exception):
                    await client.disconnect()
                raise RubikaError(
                    "Rubika session is invalid or revoked. "
                    "Re-run `python session_rubika.py` to re-authenticate."
                ) from exc
            except RPCError as exc:
                with contextlib_suppress(Exception):
                    await client.disconnect()
                raise RubikaError(f"rubika connect failed: {exc}") from exc
            self._client = client
            self._ready = True
            logger.info(
                "[rubika] logged in as %s (guid=%s)",
                getattr(me.user, "username", None) or getattr(me.user, "first_name", "?"),
                me.user.user_guid,
            )

    async def close(self) -> None:
        if self._client is None:
            return
        try:
            await self._client.disconnect()
        except Exception as exc:  # noqa: BLE001
            logger.warning("[rubika] disconnect error: %s", exc)
        self._client = None
        self._ready = False

    async def resolve_username(self, username: str) -> dict[str, Any]:
        """Look up a Rubika user by @username. Returns dict with object_guid, type, name."""
        await self.connect()
        if self._client is None:
            raise RubikaError("Rubika is not configured (session missing).")
        username = username.strip().lstrip("@")
        if not username:
            raise RubikaError("نام کاربری روبیکا خالی است.")
        try:
            result = await self._client.get_object_by_username(username)
        except RPCError as exc:
            raise RubikaError(f"lookup failed: {exc}") from exc

        user = getattr(result, "user", None)
        channel = getattr(result, "channel", None)
        target = user or channel
        if target is None:
            raise RubikaError("کاربر روبیکا پیدا نشد.")

        guid = getattr(target, "user_guid", None) or getattr(target, "channel_guid", None) \
            or getattr(target, "object_guid", None)
        if not guid:
            raise RubikaError("شناسه کاربر روبیکا پیدا نشد.")
        return {
            "object_guid": guid,
            "type": "User" if user is not None else "Channel",
            "name": getattr(target, "first_name", "") or getattr(target, "title", "") or username,
        }

    async def send_file(
        self,
        file_path: Path,
        target_username: str,
        caption: str | None = None,
    ) -> dict[str, Any]:
        """Resolve username, upload the file, and post it to the target's DM."""
        if not file_path.exists():
            raise RubikaError(f"فایل پیدا نشد: {file_path}")

        async with self._lock:
            await self.connect()
            if self._client is None:
                raise RubikaError("Rubika uploader غیرفعال است.")

            target = await self.resolve_username(target_username)
            logger.info(
                "[rubika] sending %s (%d bytes) to %s (%s)",
                file_path.name, file_path.stat().st_size, target["name"], target["object_guid"],
            )

            with tempfile.TemporaryDirectory(prefix="rb_zip_") as tmp_dir:
                zip_path = Path(tmp_dir) / RUBIKA_ZIP_NAME
                await asyncio.to_thread(_zip_file, file_path, zip_path)
                zip_size = zip_path.stat().st_size
                logger.info(
                    "[rubika] zipped to %s (%d bytes)", zip_path.name, zip_size,
                )
                last_logged_pct = -1
                start_ts = time.monotonic()
                last_chunk_ts = start_ts

                def _progress(total: int, uploaded: int) -> None:
                    nonlocal last_logged_pct, last_chunk_ts
                    now = time.monotonic()
                    elapsed = now - start_ts
                    since_last = now - last_chunk_ts
                    last_chunk_ts = now
                    pct = int(uploaded * 100 / total) if total else 100
                    rate = (uploaded / elapsed / 1024) if elapsed > 0 else 0
                    if pct >= last_logged_pct + 5 or uploaded >= total:
                        last_logged_pct = pct
                        logger.info(
                            "[rubika] upload %d%% (%d/%d bytes, %.1f KB/s, +%.1fs)",
                            pct, uploaded, total, rate, since_last,
                        )

                logger.info(
                    "[rubika] send_message start (timeout=%ds, size=%d B)",
                    self._settings.rubika_upload_timeout, zip_size,
                )
                try:
                    update = await asyncio.wait_for(
                        self._client.send_message(
                            object_guid=target["object_guid"],
                            text=caption or None,
                            file_inline=str(zip_path),
                            type="File",
                            file_name=RUBIKA_ZIP_NAME,
                            callback=_progress,
                        ),
                        timeout=self._settings.rubika_upload_timeout,
                    )
                except asyncio.TimeoutError as exc:
                    elapsed = time.monotonic() - start_ts
                    logger.error(
                        "[rubika] TIMEOUT after %.1fs, last_pct=%d, idle_for=%.1fs",
                        elapsed, last_logged_pct, time.monotonic() - last_chunk_ts,
                    )
                    raise RubikaError(
                        f"upload timed out at {last_logged_pct}% after {elapsed:.0f}s"
                    ) from exc
                except RPCError as exc:
                    logger.exception("[rubika] RPCError during send_message")
                    raise RubikaError(f"send failed: {exc}") from exc
                except Exception as exc:
                    logger.exception("[rubika] unexpected error during send_message")
                    raise RubikaError(f"send failed: {exc!r}") from exc

            message_id = getattr(update, "message_id", None) or getattr(update, "id", None)
            logger.info("[rubika] delivered, message_id=%s", message_id)
            return {
                "object_guid": target["object_guid"],
                "name": target["name"],
                "message_id": message_id,
            }


def _zip_file(src: Path, dst: Path) -> None:
    with zipfile.ZipFile(dst, "w", compression=zipfile.ZIP_STORED) as zf:
        zf.write(src, arcname=src.name)
